<?php

namespace Copiaincolla\MetaTagsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MetatagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetatagRepository extends EntityRepository
{
}